import type { Metadata } from "next";
import "../globals.css";
import { Header } from "@/components/layouts/Header";
import { Footer } from "@/components/layouts/Footer";

import localFont from "next/font/local";



const myFont = localFont({
  src: "../../public/fonts/IBMPlexSans.ttf", // adjust path as needed
  weight: "400", // optional
  style: "normal", // optional
})

export const metadata: Metadata = {
  title: "Jar",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${myFont.className} antialiased`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
