export const TEAM_MEMBERS = [
  {
    name: "Tom Glory",
    position: "Project Manager",
    image: "jar_man_face.jpg",
    twitter: "",
    facebook: "",
    instagram: "",
  },
  {
    name: "John Lewis",
    position: "Event Manager",
    image: "jar_man_face.jpg",
    twitter: "",
    facebook: "",
    instagram: "",
  },
  {
    name: "Anna Sanders",
    position: "Creative Director",
    image: "jar_man_face.jpg",
    twitter: "",
    facebook: "",
    instagram: "",
  },
  {
    name: "Brian Long",
    position: "Speaker",
    image: "jar_man_face.jpg",
    twitter: "",
    facebook: "",
    instagram: "",
  },
  {
    name: "Lisa Parker",
    position: "Staff Manager",
    image: "jar_man_face.jpg",
    twitter: "",
    facebook: "",
    instagram: "",
  },
  {
    name: "Rosalia Bell",
    position: "Videographer",
    image: "jar_man_face.jpg",
    twitter: "",
    facebook: "",
    instagram: "",
  },
];
